apiVersion: apps/v1
kind: Deployment
metadata:
  name: products
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products
  template:
    metadata:
      labels:
        app: products
    spec:
      containers:
      - name: products
        image: gcr.io/blackbox-342109/products:1.0.0
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: products
spec:
  type: ClusterIP
  selector:
    app: products
  ports:
  - name: grpc
    port: 8082
    targetPort: 8082