# Technically different deployments and services arent needed
# This one was created to test the service using ClusterIp
# and the frontend deployment with that image
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment-clusterip
spec:
  replicas: 1
  selector:
    matchLabels:
      name: frontend
      app: micro
  template:
    metadata:
      labels:
        name: frontend
        app: micro
    spec:
      containers:
      - name: frontend
        image: gcr.io/blackbox-342109/frontend:latest
---

apiVersion: v1
kind: Service
metadata:
  name: frontend-service-clusterip
spec:
  type: LoadBalancer
  selector:
    name: frontend
    app: micro
  ports:
  - name: http
    port: 80
    targetPort: 8080