apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders
spec:
  replicas: 1
  selector:
    matchLabels:
      name: orders
      app: micro
  template:
    metadata:
      labels:
        name: orders
        app: micro
    spec:
      containers:
      - name: orders
        image: gcr.io/blackbox-342109/orders:latest
