apiVersion: apps/v1
kind: Deployment
metadata:
  name: products
spec:
  replicas: 1
  selector:
    matchLabels:
      name: products
      app: micro
  template:
    metadata:
      labels:
        name: products
        app: micro
    spec:
      containers:
      - name: products
        image: gcr.io/blackbox-342109/products:latest
